version: '3.8'

services:
  # VaultRunner application
  vaultrunner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vaultrunner
    environment:
      # Vault configuration
      - VAULT_ADDR=${VAULT_ADDR:-http://vault:8200}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_NAMESPACE=${VAULT_NAMESPACE}
      
      # VaultRunner configuration
      - VAULTRUNNER_LOG_LEVEL=${VAULTRUNNER_LOG_LEVEL:-info}
      - VAULTRUNNER_DRY_RUN=${VAULTRUNNER_DRY_RUN:-false}
      - VAULTRUNNER_ENV=docker
    
    volumes:
      # Mount current directory for config files and .vault directory
      - .:/workspace:rw
      
      # Mount Docker socket for Docker integration (use with caution)
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
      # Optional: Mount Vault config directory
      - vault-config:/vault/config:ro
    
    working_dir: /workspace
    command: ["--help"]
    
    # Security settings
    user: "1000:1000"  # Adjust to match your user ID
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    
    # Network configuration
    networks:
      - vaultrunner-network
    
    # Dependencies
    depends_on:
      - vault
    
    # Health check
    healthcheck:
      test: ["CMD", "./vaultrunner", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3

  # HashiCorp Vault for development/testing
  vault:
    image: hashicorp/vault:1.15
    container_name: vault-dev
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_ROOT_TOKEN:-myroot}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    
    ports:
      - "8200:8200"
    
    volumes:
      - vault-data:/vault/data
      - vault-config:/vault/config
      - vault-logs:/vault/logs
    
    cap_add:
      - IPC_LOCK
    
    command: ["vault", "server", "-dev"]
    
    networks:
      - vaultrunner-network
    
    # Health check
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Optional: Vault UI (separate from dev mode)
  vault-ui:
    image: hashicorp/vault:1.15
    container_name: vault-ui
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_ROOT_TOKEN:-myroot}
    
    ports:
      - "8201:8200"
    
    depends_on:
      - vault
    
    networks:
      - vaultrunner-network
    
    profiles:
      - ui

# Networks
networks:
  vaultrunner-network:
    driver: bridge
    name: vaultrunner-net

# Volumes
volumes:
  vault-data:
    name: vault-data
  vault-config:
    name: vault-config
  vault-logs:
    name: vault-logs